### ISSUE TITLE
Why does the tagName default to `div`?

### ISSUE THREAD

**Issue by jaller94** [syntax-tree/hast-util-parse-selector#4]
I wonder why `tagName` defaults to div. The CSS selectors `.foo` and `div.foo` differ, but their output seems to be the same in this library.

https://github.com/syntax-tree/hast-util-parse-selector/blob/6d9e033f2df51cc4c3616f295714107496364191/test.js#L7-L16

I would expect tagName to default to `undefined` (or `null`), so I know that a given selector does not contain a tagName part.

**Comment by wooorm** [comment]
@jaller94 Because this library is used to create elements, inside something like [hastscript](https://github.com/syntax-tree/hastscript), and no tag name would create invalid elements. This is similar to how other hyperscript syntaxes work (like [hyperscript](https://github.com/hyperhype/hyperscript)).
